#!/bin/sh


TARGET=$(ls target/*.jar 2>/dev/null)
if [ -z "$TARGET" ]; then
    echo "No jar file in target/, try 'mvn package'".
    exit 1
fi

if [ ! .mvn-classpath -nt pom.xml ]; then
  mvn dependency:build-classpath -Dmdep.outputFile=.mvn-classpath -q
fi

CP=$(cat .mvn-classpath)

MAIN=$(ls src/main/java/edu/brown/cs/*/*/Main.java)
[ -z "$MAIN" ] && echo "You need a Main.java" && exit 1
[ ! -e "$MAIN" ] && echo "You can only have one Main.java" && exit 1
STUDENT=$(basename $(dirname $(dirname $MAIN)))
MAINPKG=$(basename $(dirname $MAIN))

PATHSEP=":"
if [ "$OSTYPE" = 'cygwin' -o "$OSTYPE" = 'msys' ]; then
    PATHSEP=";"
fi

# The symbol "$@" passes the command-line arguments from
# this script to the Java program.
java -ea -cp "$TARGET$PATHSEP$CP" edu.brown.cs.$STUDENT.$MAINPKG.Main "$@"
